---
- hosts: all  # noqa: name[play]
  become: true
  vars:
      is_container: false

  roles:
  - role: "{{ playbook_dir }}"
    rhel7stig_system_is_container: "{{ is_container | default(false) }}"
    rhel7stig_skip_for_travis: false
