---

- name: "MEDIUM | RHEL-07-040810 | AUDIT | The Red Hat Enterprise Linux operating system access control program must be configured to grant or deny system access to specific hosts and services."
  ansible.builtin.shell: iptables-save
  register: rhel_07_040810_iptables_audit
  changed_when: false
  failed_when: false
  when:
      - rhel7stig_start_firewall_service
  tags:
      - RHEL-07-040810
      - firewall

- name: "MEDIUM | RHEL-07-040810 | AUDIT | The Red Hat Enterprise Linux operating system access control program must be configured to grant or deny system access to specific hosts and services."
  ansible.builtin.debug:
      msg: "The following task output is the iptables-save output in full from {{ ansible_hostname }}:"
  changed_when: true
  when:
      - rhel_07_040810_iptables_audit.stdout_lines is defined
      - rhel7stig_start_firewall_service
  tags:
      - RHEL-07-040810
      - firewall

- name: "MEDIUM | RHEL-07-040810 | AUDIT | The Red Hat Enterprise Linux operating system access control program must be configured to grant or deny system access to specific hosts and services."
  ansible.builtin.debug: var=rhel_07_040810_iptables_audit.stdout_lines
  changed_when: false
  when:
      - rhel_07_040810_iptables_audit.stdout_lines is defined
      - rhel7stig_start_firewall_service
  tags:
      - RHEL-07-040810
      - firewall

- name: "MEDIUM | RHEL-07-040810 | AUDIT | The Red Hat Enterprise Linux operating system access control program must be configured to grant or deny system access to specific hosts and services."
  ansible.builtin.debug:
      msg: "Warning!! We could pull no configured rules for {{ rhel7stig_firewall_service }} on {{ ansible_hostname }}! This is a finding per RHEL-07-040810 - The Red Hat Enterprise Linux operating system access control program must be configured to grant or deny system access to specific hosts and services."
  changed_when: true
  when:
      - rhel_07_040810_iptables_audit.stdout_lines is not defined
      - rhel7stig_start_firewall_service
  tags:
      - RHEL-07-040810
      - firewall
