Vagrant.configure("2") do |config|

  # CentOS 7
  config.vm.define "centos7-stig" do |centos7|
    centos7.vm.box = "samdoran/centos7"
    centos7.vm.hostname = "centos7-stig"
    centos7.vm.network "forwarded_port", guest: 22, host: 2200, id: 'ssh'
    config.vm.provider "virtualbox" do |vbox|
      vbox.name = "centos7-stig"
      vbox.cpus = 2
      vbox.memory = 512
    end
  end

  # RHEL 7
  config.vm.define "rhel7-stig" do |rhel7|
    rhel7.vm.box = "samdoran/rhel7"
    rhel7.vm.hostname = "rhel7-stig"
    rhel7.vm.network "forwarded_port", guest: 22, host: 2201, id: 'ssh'
    config.vm.provider "virtualbox" do |vbox|
      vbox.name = "rhel7-stig"
      vbox.cpus = 2
      vbox.memory = 512
    end
  end

  config.vm.provision "apply_stig", type: "ansible" do |play|
    play.playbook = "vagrant_provision.yml"
    play.extra_vars = "extra_vars_vagrant.yml"
  end

end
