# This is a basic workflow to help you get started with Actions

name: DevelToMain

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the devel branch
on:
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Refactr pipeline for devel pull request/merge
      - name: Refactr - Run Pipeline (to main)
       # You may pin to the exact commit or the version.
        # uses: refactr/action-run-pipeline@be91e2796aa225268e4685c0e01a26d5f800cd53
        uses: refactr/action-run-pipeline@v0.1.2
        with:
          # API token
          api_token: '${{ secrets.REFACTR_KEY }}'
          # Project ID
          project_id: 5f47f0c4a13c7b18373e5556
          # Job ID
          job_id: 6040fe0cf7b21a22e11cf3b8
          # Variables
          variables: '{ "gitrepo": "https://github.com/ansible-lockdown/RHEL7-STIG.git", "image": "ami-098f55b4287a885ba", "username": "centos" }'
          # Refactr API base URL
          api_url: # optional
