# This is the workflow for sending a welcome message when a new contributor creates a new issue

name: new_contrib_message

# Controls when the action will run.
# Triggers the workflow on push or pull request
# events but only for the devel branch
on:
  issues:
    types: [opened]

# A workflow run is made up of one or more jobs
# that can run sequentially or in parallel
jobs:
  # This will create messages for first time contributers and direct them to the Discord server
  welcome:
      runs-on: ubuntu-latest

      steps:
          - uses: actions/first-interaction@v1.1.0
            with:
                repo-token: ${{ secrets.GITHUB_TOKEN }}
                issue-message: |-
                  Congrats on opening your first Issue and thank you for taking the time to help improve Ansible-Lockdown!
                  Please join in the conversation happenign on the [Discord Server](https://discord.gg/ArDjfhY8) as well.