---

# This is a basic workflow to help you get started with Actions

name: update galaxy

# Controls when the action will run.
# Triggers the workflow on merge request events to the main branch
on:
  push:
    branches:
      - main
jobs:
    update_role:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: hspaans/ansible-galaxy-action@master
          with:
            api_key: ${{ secrets.GALAXY_API_KEY }}
